Project/urls.py
from django.contrib import admin
from django.urls import path, include
from web import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('monitor/', include('monitor.urls')),
    path('web/',include('web.urls'))
]

monitor/urls.py
from django.urls import path
from . import views


app_name = 'monitor'
urlpatterns = [
    path('', views.index, name='index'),
    path('start', views.start, name='start'),
    path('stop', views.stop, name='stop'),
    path('stream', views.stream, name='stream')
]

web/urls.py
from django.urls import path, include
from . import views

app_name = 'web'
urlpatterns = [
    path('', views.index),
    path('login_page/', views.login_page, name='login_page'),
    path('login/', views.login, name='login'),
    path('change_password_page/', views.change_password_page, name='change_password_page'),
    path('change_password/', views.change_password, name='change_password'),
    path('logout/', views.logout, name='logout'),
]

monitor/models.py
from django.db import models

# Create your models here.

web/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=100, unique=True)
    password = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    def __str__(self):
        return self.name

web/forms.py
from django import forms

class user_form(forms.Form):
    username = forms.CharField(label="用户名", max_length=128)
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput)

class change_form(forms.Form):
    username = forms.CharField(label='用户名', max_length=128)
    old_password = forms.CharField(label='原密码', max_length=256, widget=forms.PasswordInput)
    new_password = forms.CharField(label='新密码', max_length=256, widget=forms.PasswordInput)

monitor/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, StreamingHttpResponse
from .MobileNetSSD.videoCamera import gen, VideoCamera
from django.views.decorators import gzip

# Create your views here.
def index(request):
    user_cookie = request.COOKIES.get('username', '')
    if user_cookie:
        return render(request, 'monitor/index.html', { 'username': user_cookie })
    else:
        return HttpResponseRedirect('/web/')

def start(request):
    global vc
    vc = VideoCamera('./monitor/MobileNetSSD/deploy.prototxt', './monitor/MobileNetSSD/MobileNetSSD_deploy.caffemodel')
    return HttpResponse()

def stop(request):
    global vc
    del vc
    return HttpResponse()

def stream(request):
    global vc
    try:
        return StreamingHttpResponse(gen(vc),content_type="multipart/x-mixed-replace;boundary=frame")
    except HttpResponseServerError as e:
        print("aborted")

web/views.py
from django.shortcuts import render, render_to_response, redirect
from django import forms
from .models import User
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseServerError
from . import models
from . forms import user_form
from . forms import change_form

# Create your views here.

def index(request):
    user_cookie = request.COOKIES.get('username', '')
    if user_cookie:
        try:
            user = models.User.objects.get(name=user_cookie)
            return HttpResponseRedirect('/monitor/')
        except:
            return render(request, 'web/index.html')
    else:
        return render(request, 'web/index.html')

def login_page(request):
    user_cookie = request.COOKIES.get('username', '')
    if user_cookie:
        return HttpResponseRedirect('/monitor/')
    else:
        return render(request, 'web/login_page.html', { 'f1': user_form() })

def change_password_page(request):
    return render(request, 'web/change_password_page.html', { 'f1': change_form() })


def login(request):
    user_cookie = request.COOKIES.get('username', '')
    if user_cookie:
        return HttpResponseRedirect('/monitor/')
    if request.method == 'POST':
        f1 = user_form(request.POST)
        if f1.is_valid():
            username = f1.cleaned_data['username']
            password = f1.cleaned_data['password']
            try:
                user = models.User.objects.get(name=username)
                if user.password == password:
                    #return redirect('/index/')
                    #return render_to_response('http://127.0.0.1:8000/index/show') 
                    response =  HttpResponseRedirect('/monitor/')
                    response.set_cookie('username', username, max_age=600)
                    return response
                    #return render(request, '/index/show')
                else:
                    message = '密码不正确，请重新输入'
            except:
                message = '用户不存在'
        return render(request, 'web/login_page.html', { 'f1': f1, 'message': message })
    f1 = user_form()
    return render(request, 'web/login_page.html', { 'f1': f1 })

def change_password(request):
    if request.method == 'POST':
        f1 = change_form(request.POST)
        if f1.is_valid():
            username = f1.cleaned_data['username']
            old_password = f1.cleaned_data['old_password']
            new_password = f1.cleaned_data['new_password']
            user = User.objects.filter(name=username)
            if user:
                pw = User.objects.filter(name=username, password=old_password)
                if pw:
                    User.objects.filter(name=username, password=old_password).update(password=new_password)
                    return redirect('/web/')
                else:
                    message = '原密码不正确，请重新输入'
            else:
                message = '用户不存在'
            return render(request, 'web/change_password_page.html', { 'f1': f1, 'message': message })

    f1 = change_form()
    return render(request,'web/change_password_page.html', { 'f1': f1 })

def logout(request):
    if request.COOKIES['username']:
        response = HttpResponseRedirect('/web/')
        response.delete_cookie('username')
        return response

monitor/templates/monitor/index.html
<html>
    <head>
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
        <meta name="viewport" content="width=device-width, minimum-scale=0.1">
    </head>
    <body style="margin: 0px;">
        <h3> Hello, {{ username }} </h3>
        <form action="{% url 'web:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Logout">
        </form>
        
        <form id="start">
            {% csrf_token %}
            <input type="submit" value="Turn on camera">
        </form>
        <form id="stop">
            {% csrf_token %}
            <input type="submit" value="Turn off camera">
        </form>
        <img id="camera_view" style="-webkit-user-select: none;">
    </body>

    <script>
        $('#camera_view').hide();
        $('#start').submit(function(e){
            e.preventDefault();
            $.ajax({
                url:"{% url 'monitor:start'%}",
                type:'post',
                data:$('#start').serialize(),
                success: function(){
                    $('#camera_view').show();
                    $('#camera_view').attr('src',"{% url 'monitor:stream' %}");
                }
            });
        });

        $('#stop').submit(function(e){
            e.preventDefault();
            $.ajax({
                url:"{% url 'monitor:stop'%}",
                type:'post',
                data:$('#stop').serialize(),
                success: function(){
                    $('#camera_view').hide();
                    $('#camera_view').attr('src',"");
                }
            });
        });
    </script>
</html>

templates/change_password_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码</title>
</head>
<body>
<h1>修改密码</h1>
<form class="form-changepassword" action="{% url 'change_password' %}" method="post" enctype="multipart/form-data">
    {% if message %}
               <div class="alert alert-warning">{{ message }}</div>
           {% endif %}
    {% csrf_token %}
    {{ f1 }}
    <button type="submit">确定</button>
</form>
</body>
</html>

templates/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码</title>
</head>
<body>
<h1>修改密码</h1>
<form class="form-changepassword" action="changepassword.html" method="post" enctype="multipart/form-data">
    {% if message %}
               <div class="alert alert-warning">{{ message }}</div>
           {% endif %}
    {% csrf_token %}
    {{ f1 }}
    <button type="submit">确定</button>
</form>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
</head>
<body>
<h1>Welcome</h1>
<br>
<a href="{% url 'login_page' %}">登陆</a>
<br>
<a href="{% url 'change_password_page' %}">修改密码</a>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登陆</title>
</head>
<body>
<h1>登陆</h1>
<form class = 'form-login' action="login.html" method="post" enctype="multipart/form-data">
    {% if message %}
               <div class="alert alert-warning">{{ message }}</div>
           {% endif %}
    {% csrf_token %}
    {{ f1 }}
    <!--<input type="submit" value="登陆">-->
    <button type="submit">登陆</button>
</form>
</body>
</html>

templates/login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登陆</title>
</head>
<body>
<h1>登陆</h1>
<form class ='form-login' action="{% url 'login' %}" method="post" enctype="multipart/form-data">
    {% if message %}
               <div class="alert alert-warning">{{ message }}</div>
           {% endif %}
    {% csrf_token %}
    {{ f1 }}
    <!--<input type="submit" value="登陆">-->
    <button type="submit">登陆</button>
</form>
</body>
</html>

templates/show.html
<html>
    <head>
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
        <meta name="viewport" content="width=device-width, minimum-scale=0.1">
    </head>
    <body style="margin: 0px;">
        <h3> Hello, {{ username }} </h3>
        <form action="{% url 'logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Logout">
        </form>
        
        <form id="start">
            {% csrf_token %}
            <input type="submit" value="Turn on camera">
        </form>
        <form id="stop">
            {% csrf_token %}
            <input type="submit" value="Turn off camera">
        </form>
        <img id="camera_view" style="-webkit-user-select: none;">
    </body>

    <script>
        $('#camera_view').hide();
        $('#start').submit(function(e){
            e.preventDefault();
            $.ajax({
                url:"{% url 'start'%}",
                type:'post',
                data:$('#start').serialize(),
                success: function(){
                    $('#camera_view').show();
                    $('#camera_view').attr('src',"{% url 'stream' %}");
                }
            });
        });

        $('#stop').submit(function(e){
            e.preventDefault();
            $.ajax({
                url:"{% url 'stop'%}",
                type:'post',
                data:$('#stop').serialize(),
                success: function(){
                    $('#camera_view').hide();
                    $('#camera_view').attr('src',"");
                }
            });
        });
    </script>
</html>

web/templates/web/change_password_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码</title>
</head>
<body bgcolor="#C0C0C0">
<h1 style="text-align: center">修改密码</h1>
<form class="form-changepassword" action="{% url 'web:change_password' %}" method="post" enctype="multipart/form-data">
    {% if message %}
               <div class="alert alert-warning">{{ message }}</div>
           {% endif %}
    {% csrf_token %}
    {{ f1 }}
    <button type="submit">确定</button>
</form>
</body>
</html>

web/templates/web/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
</head>
<body bgcolor="#C0C0C0">
<br><br>
<h1 style="text-align: center">Welcome</h1>
<br><br><br>
<div id = 'main' style="text-align: center">
<a href="{% url 'web:login_page' %}">登陆</a>
<br><br>
<a href="{% url 'web:change_password_page' %}">修改密码</a>
</div>
</body>
</html>

web/templates/web/login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登陆</title>
</head>
<body bgcolor="#C0C0C0">
<h1 style="text-align: center">登陆</h1>
<form class ='form-login' action="{% url 'web:login' %}" method="post" enctype="multipart/form-data">
    {% if message %}
               <div class="alert alert-warning">{{ message }}</div>
           {% endif %}
    {% csrf_token %}
    {{ f1 }}
    <!--<input type="submit" value="登陆">-->
    <button type="submit">登陆</button>
</form>
</body>
</html>